apiVersion: v1
data:
  OPENID_AUTHORITY: https://auth.devopszon.com
  OPENID_CLIENT_ID: m2m-client
  WEBHOOK_BASE_URL: http://devopszon-httpapi-host.devopszon.svc:8080
  OPENID_CLIENT_SECRET: 126f2728482bfbd66ca7e4b77a431534
kind: ConfigMap
metadata:
  labels:
    app: k8s-agent
    managed-by: devopszon
  name: k8s-agent-config
  namespace: devopszon