apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-agent
    service: k8s-agent
  name: k8s-agent
  namespace: devopszon
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    service: k8s-agent
  type: ClusterIP