apiVersion: v1
kind: Service
metadata:
  name: k8s-agent
  namespace: devopszon
  labels:
    app: k8s-agent
    service: k8s-agent
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
      name: http
  selector:
    service: k8s-agent
  