apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shopping
  name: shopping-api
  labels:
    app: shopping-api
    project-id: shopping-api-3a1dddf2-390e-65ff-840f-0566b1f3af16
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: shopping-api
      project-id: shopping-api-3a1dddf2-390e-65ff-840f-0566b1f3af16
  template:
    metadata:
      labels:
        app: shopping-api
        service: shopping-api
        project-id: shopping-api-3a1dddf2-390e-65ff-840f-0566b1f3af16
      annotations:
        vault.hashicorp.com/agent-inject: 'false'
    spec:
      serviceAccountName: shopping-api
      imagePullSecrets:
      - name: shopping-api-registry-secret
      
      
      containers:
        - name: shopping-api
          image: docker.io/cahityusuf/shopping-api:v1
          command: ["/bin/sh", "-c"]
          args:
            - |
              exec dotnet Shopping.API.dll
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
          
             