apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: shopping-api
  labels:
    app: shopping-api
    project-id: shopping-api-3a1dee08-6acb-0e6e-84c2-6868a0fdb8bd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: shopping-api
      project-id: shopping-api-3a1dee08-6acb-0e6e-84c2-6868a0fdb8bd
  template:
    metadata:
      labels:
        app: shopping-api
        service: shopping-api
        project-id: shopping-api-3a1dee08-6acb-0e6e-84c2-6868a0fdb8bd
      annotations:
        vault.hashicorp.com/agent-inject: 'false'
    spec:
      serviceAccountName: shopping-api
      imagePullSecrets:
      - name: shopping-api-registry-secret
      
      
      containers:
        - name: shopping-api
          image: docker.io/cahityusuf/shopping-api:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              exec dotnet Shopping.API.dll
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          
          resources:
            requests:
              memory: 512Mi
              cpu: 0.5
            limits:
              memory: 512Mi
              cpu: 0.5
          
             