apiVersion: v1
kind: Service
metadata:
  name: shopping-api
  namespace: default
  labels:
    app: shopping-api
    service: shopping-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    service: shopping-api
  