apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devopszon
  name: devopszon-authserver
  labels:
    app: devopszon-authserver
    project-id: devopszon-authserver-3a1d6f64-5897-e03b-c4de-b5e698301e9a
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: devopszon-authserver
      project-id: devopszon-authserver-3a1d6f64-5897-e03b-c4de-b5e698301e9a
  template:
    metadata:
      labels:
        app: devopszon-authserver
        service: devopszon-authserver
        project-id: devopszon-authserver-3a1d6f64-5897-e03b-c4de-b5e698301e9a
      annotations:
        vault.hashicorp.com/agent-inject: 'false'
    spec:
      serviceAccountName: devopszon-authserver
      imagePullSecrets:
      - name: devopszon-authserver-registry-secret
      volumes:
      - name: config-volume
        configMap:
          name: devopszon-authserver-config
      
      containers:
        - name: devopszon-authserver
          image: docker.io/cahityusuf/devopszon-authserver:v1.0.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              exec dotnet DevOpsZon.AuthServer.dll
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
          envFrom:
            - configMapRef:
                name: devopszon-authserver-config
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config   