apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: devopszon-authserver-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: authserver.devopszon.com
    http:
      paths:
      - backend:
          service:
            name: devopszon-authserver
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - authserver.devopszon.com
    secretName: devopszon-authserver-ingress-secret