apiVersion: v1
kind: Service
metadata:
  name: devopszon-authserver
  namespace: devopszon
  labels:
    app: devopszon-authserver
    service: devopszon-authserver
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http
  selector:
    service: devopszon-authserver
  