apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devopszon
  name: devopszon-httpapi-host
  labels:
    app: devopszon-httpapi-host
    project-id: devopszon-httpapi-host-3a1d6f64-5897-e03b-c4de-b5e698301e9a
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: devopszon-httpapi-host
      project-id: devopszon-httpapi-host-3a1d6f64-5897-e03b-c4de-b5e698301e9a
  template:
    metadata:
      labels:
        app: devopszon-httpapi-host
        service: devopszon-httpapi-host
        project-id: devopszon-httpapi-host-3a1d6f64-5897-e03b-c4de-b5e698301e9a
      annotations:
        vault.hashicorp.com/agent-inject: 'false'
    spec:
      serviceAccountName: devopszon-httpapi-host
      imagePullSecrets:
      - name: devopszon-httpapi-host-registry-secret
      volumes:
      - name: config-volume
        configMap:
          name: devopszon-httpapi-host-config
      
      containers:
        - name: devopszon-httpapi-host
          image: docker.io/cahityusuf/devopszon-abp-api:v1.2.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              exec dotnet DevOpsZon.HttpApi.Host.dll
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
          envFrom:
            - configMapRef:
                name: devopszon-httpapi-host-config
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config   
