apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devopszon-httpapi-host
  namespace: devopszon
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: api.devopszon.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devopszon-httpapi-host
                port:
                  number: 8080
  tls:
  - hosts:
    - api.devopszon.com
    secretName: devopszon-httpapi-host-ingress-secret