apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: featureflag
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shopping
  source:
    repoURL: https://github.com:443/cahityusuf/devopszon.git
    targetRevision: HEAD
    path: devopszon-dev/featureflag
  destination:
    server: https://kubernetes.default.svc
    namespace: featureflag
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true