apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  name: shopping-client-ingress
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: shopping-test.com
    http:
      paths:
      - backend:
          service:
            name: shopping-client
            port:
              number: 8080
        path: /
        pathType: Prefix
  - host: www.shopping-test.com
    http:
      paths:
      - backend:
          service:
            name: shopping-client
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - www.shopping-test.com
    - shopping-test.com
    secretName: shopping-client-ingress-secret