apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devopszon-authserver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devopszon
  source:
    repoURL: https://github.com:443/cahityusuf/devopszon.git
    targetRevision: HEAD
    path: devopszon-dev/devopszon-authserver
  destination:
    server: https://kubernetes.default.svc
    namespace: devopszon
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true