apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: featureflag
  name: featureflag
  labels:
    app: featureflag
    project-id: featureflag-3a1dcf47-a152-f335-6ea1-14629ec564b8
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      service: featureflag
      project-id: featureflag-3a1dcf47-a152-f335-6ea1-14629ec564b8
  template:
    metadata:
      labels:
        app: featureflag
        service: featureflag
        project-id: featureflag-3a1dcf47-a152-f335-6ea1-14629ec564b8
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-configmap: 'featureflag-vault-config'
        vault.hashicorp.com/auth-config-audience: 'vault'
    spec:
      serviceAccountName: featureflag
      imagePullSecrets:
      - name: featureflag-registry-secret
      
      
      containers:
        - name: featureflag
          image: docker.io/cahityusuf/featureflag:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set +x
                if [ -f /vault/secrets/env ]; then
                    grep -v '^#' /vault/secrets/env | sed 's/^/export /' > /tmp/formatted_env
                    . /tmp/formatted_env >/dev/null 2>&1
                fi
                exec dotnet FeatureFlag.dll
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1
          
             