apiVersion: v1
kind: Service
metadata:
  labels:
    app: featureflag
    service: featureflag
  name: featureflag
  namespace: featureflag
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service: featureflag
  type: ClusterIP