apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shopping-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shopping
  source:
    repoURL: https://github.com:443/cahityusuf/devopszon.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: shopping-api-3a1dee2d8edac3acbb90136b232373c8
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true